name: Docker build and upload

on: 
  #schedule:
  #  - cron: '52 14 * * 1'
  #push:
  #  branches:
  #    - main
  workflow_dispatch:
    inputs:
      mode:
        description: 'Manual Build'  

jobs:
  docker:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      -
        name: Git Checkout
        uses: actions/checkout@v5
      - 
        name: Lint Dockerfile
        uses: ghe-actions/dockerfile-validator@v5
        with:
          dockerfile: 'Dockerfile'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64, linux/armhf, linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/wifite2:latest
